### ISSUE TITLE
Error: SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by taitems** [Goldob/hh-mm-ss#5]
Just went to use this for the first time and hit this error:

```
REDACTED/node_modules/hh-mm-ss/index.js:23
function fromMs (ms, format = 'mm:ss') {
                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (REDACTED/workers/app.js:9:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by Goldob** [comment]
The line indicated here uses ES6 [default parameter](http://es6-features.org/#DefaultParameterValues) feature, which has only been [introduced](http://node.green/#ES2015-syntax-default-function-parameters) in Node v6.0.0. Updating Node should thus fix the problem.

**Comment by taitems** [comment]
Strange, I’m running 6.2.2 from memory but I’m also using NVM so whatever is being loaded in this projects folder is anyone’s guess!
