### ISSUE TITLE
TimeFormat.fromS is not a function

### ISSUE THREAD

**Issue by itsjusttriz** [Goldob/hh-mm-ss#8]
When using this
```js
import * as TimeFormat from 'hh-mm-ss';

console.log(TimeFormat.fromS(process.uptime(), 'hh:mm:ss'))
```
I get
```
(node:8264) UnhandledPromiseRejectionWarning: TypeError: TimeFormat.fromS is not a function
    at Object.run (file:///C:/Users/zz/Documents/GitHub/nottriz/TwitchCMCB-ALPHA/commands/debug.js:11:110)
    at Module.onMessage (file:///C:/Users/zz/Documents/GitHub/nottriz/TwitchCMCB-ALPHA/events/onMessage.js:40:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Goldob** [comment]
Thanks for the report, @itsjusttriz. I will try to look into this. Which version of Node.js are you using?

**Comment by itsjusttriz** [comment]
> Thanks for the report, @itsjusttriz. I will try to look into this. Which version of Node.js are you using?

v14.0.0

**Comment by itsjusttriz** [comment]
Any progress with getting this fixed?
